global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "exporter"
    static_configs:
      - targets: ["exporter:10009"]

  - job_name: "metrics_handler"
    static_configs:
      - targets: ["metrics_handler:10011"]

storage:
  tsdb:
    out_of_order_time_window: 5m
