global:
  scrape_interval: 30s 
  evaluation_interval: 30s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "buddy"
    static_configs:
      - targets: ["buddy:10009"]
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
